# Workflow to sync changes from source repo        
name: Sync repo
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      security-events: write

    # Sync from Origin repo
    steps:
    - name: Checkout Target Repo
      uses: actions/checkout@v2
      with:
        ref: main
              
    - name: nxtlvlsoftware/git-subtree
      # You may pin to the exact commit or the version.
      # uses: NxtLvLSoftware/git-subtree-action@3d555981a570a2275a91c07b04b38d5e90d48c05
      uses: NxtLvLSoftware/git-subtree-action@1.1
      with:
        # Child repository to sync the subtree to (eg. owner/repository.)
        repo: https://username:${{ secrets.PAT }}@github.com/Abel-csd/OriginRepro.git
        # Path prefix in parent repo to split into child subtree (eg. src/PackageName.)
        path: TargetFolder
        # Deployment SSH key for pushing to child repo (checkout out deployment tokens for single repos or bot accounts for multi-repos/orgs.)
        deploy_key: ${{ secrets.PAT }}
        # Create (or mirror) a tag on the child subtree repository (branch or tag ref that triggered the workflow when true.)
        tag: false
        # Force push to the child subtree repository (recommended for pure downstream mirrors.)
        force: false
        # Branch of child subtree repository (default is branch or tag ref that triggered the workflow.)
        branch: main         
