# Workflow to sync changes from source repo        
name: Sync repo
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      security-events: write

    # Sync from Origin repo
    steps:
    - name: Checkout Target Repo
      uses: actions/checkout@v2
      with:
        ref: main
              
    - name: jmadler/git-subtree-action
    # You may pin to the exact commit or the version.
    # uses: jmadler/git-subtree-action@12a1602b9ad34a4241ac803ac8771bfcf33261c1
      uses: jmadler/git-subtree-action@1.0
      with:
        # Token
        github_token: ${{ secrets.PAT }}
        # Git User Name
        git_name: Abel-csd
        # Git User Email
        git_email: csd0108@163.com
        # Repository
        repo: https://username:${{ secrets.PAT }}@github.com/Abel-csd/OriginRepro.git
        # Action
        action: pull
        # Branch, Commit, Ref, or Refspec
        position: main
        # Prefix
        prefix: TargetFolder
        # Force the action
        force: true
        # Squash the merge
        squash: false
            
