# Workflow to sync changes from source repo        
name: Sync repo
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      security-events: write

    # Sync from Origin repo
    steps:
    - name: Check if TargetFolder exists
      id: check_target_folder
      run: |
        if [ -d "TargetFolder" ]; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi
        
    - name: Checkout
      run: |
        git clone https://username:${{ secrets.PAT }}@github.com/Abel-csd/TargetRepro.git
        cd TargetRepro
        git checkout main

    - name: Add Subtree
      if: steps.check_target_folder.outputs.exists != 'true'
      run:
        git subtree add --prefix=TargetFolder https://username:${{ secrets.PAT }}@github.com/Abel-csd/OriginRepro.git main
        
    - name: Pull Subtree
      run: |
        git subtree pull --prefix=TargetFolder https://username:${{ secrets.PAT }}@github.com/Abel-csd/OriginRepro.git main
    
    - name: Push Change
      run: git push
