# Workflow to sync changes from source repo        
name: Sync repo
on:
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      security-events: write
    env:
      PAT: ${{ secrets.PAT }}  # Define the secret as a job-level variable

    # Sync from Origin repo
    steps:
    - name: Checkout Target Repo
      uses: actions/checkout@v2
      with:
        repository: Abel-csd/TargetRepro
        token: ${{ secrets.PAT }}

    - name: Clone Origin Repo
      run: git clone https://github.com/Abel-csd/OriginRepro.git origin-repo

    - name: Add Subtree
      run: |
        cd origin-repo
        git checkout main
        git subtree split --prefix=TargetFolder --branch=subtree-temp
        git push origin subtree-temp:subtree-temp

    - name: Merge Subtree
      run: |
        git remote add origin-repo https://github.com/Abel-csd/OriginRepro.git
        git fetch origin-repo
        git merge -s ours --no-commit subtree-temp
        git read-tree --prefix=TargetFolder -u subtree-temp
        git commit -m "Merge subtree from OriginRepro"
        git push origin main

    - name: Clean Up
      run: rm -rf origin-repo
