# Workflow to sync changes from source repo        
name: Sync repo
on:
  workflow_dispatch:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      security-events: write

    # Sync from Origin repo
    steps:
    - name: Checkout Target Repo
      uses: actions/checkout@v2
      with:
        ref: main
        
    - name: Check if TargetFolder exists
      id: check_target_folder
      run: |
        if [ -d "TargetFolder" ]; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi
      
    - name: Pull Subtree
      run: |
        git config --global user.email "csd0108@163.com"
        git config --global user.name "Abel-csd"  

    - name: Add Subtree
      if: steps.check_target_folder.outputs.exists != 'true'
      run: git subtree add --prefix=TargetFolder https://username:${{ secrets.PAT }}@github.com/Abel-csd/OriginRepro.git main

    - name: Pull Subtree
      run: git subtree pull --prefix=TargetFolder https://username:${{ secrets.PAT }}@github.com/Abel-csd/OriginRepro.git main --allow-unrelated-histories

    - name: Git Push Action
      run: git push
          
