# Workflow to sync changes from source repo        
name: Sync repo
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: windows-latest
    permissions:
      contents: write
      actions: read
      security-events: write

    # Sync from Origin repo
    steps:
    - name: Checkout
      run: |
        git clone https://username:${{ secrets.PAT }}@github.com/Abel-csd/TargetRepro.git
        cd TargetRepro
        git checkout main
        git subtree pull --prefix=TargetFolder https://username:${{ secrets.PAT }}@github.com/Abel-csd/OriginRepro.git main
        git push
