# Workflow to sync changes from source repo        
name: Sync repo
on:
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      security-events: write
    env:
      PAT: ${{ secrets.PAT }}  # Define the secret as a job-level variable

    # Sync from Origin repo
    steps:
    - name: Checkout Target Repo
      uses: actions/checkout@v2
      with:
        repository: Abel-csd/TargetRepro
        token: ${{ env.PAT }}
    
    - name: Add Subtree
      run: git subtree add --prefix=TargetFolder https://username:${{ env.PAT }}@github.com/Abel-csd/OriginRepro.git main

    - name: Pull Subtree
      run: git subtree pull --prefix=TargetFolder https://username:${{ env.PAT }}@github.com/Abel-csd/OriginRepro.git main

    - name: Commit change
      run: |
        git add .
        git commit -m "Sync changes from OriginRepro to TargetFolder"
        git push origin main
